name: Lawis-Windows 

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'CDR BAŞLATMA KODU'
        required: true
      pincode:
        description: '6 HANELİ ŞİFRE'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Disable Windows Firewall
      run: |
        powershell -Command "Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False"

    - name: Download and Install Chrome
      run: ./setup.ps1


    - name: Download and Install Chrome Remote Desktop
      run: |
        powershell -Command "
        $remoteDesktopUrl = 'https://dl.google.com/chrome-remote-desktop/chrome_remote_desktop_installer.exe';
        $remoteDesktopInstaller = \"$env:TEMP\\chrome_remote_desktop_installer.exe\";
        Invoke-WebRequest -Uri $remoteDesktopUrl -OutFile $remoteDesktopInstaller;
        Start-Process -FilePath $remoteDesktopInstaller -ArgumentList '/silent /install' -Wait;
        Remove-Item -Path $remoteDesktopInstaller -Force -ErrorAction SilentlyContinue;
        "

    - name: Starting CRD
      run: |
        powershell -Command "
        Write-Host 'Starting Chrome Remote Desktop with provided authentication code and PIN';
        Write-Host 'Auth Code: ${{ github.event.inputs.authcode }}';
        Write-Host 'PIN Code: ${{ github.event.inputs.pincode }}';
        # Burada CRD başlatma komutlarını ekleyin
        "

    - name: Keep Alive
      run: |
        powershell -Command "
        Write-Host 'Keeping the workflow alive...';
        while ($true) {
          Start-Sleep -Seconds 60
        }
        "
